baseURL = ""
canonifyURLs=true
pluralizeListTitles = false
summaryLength   = 25

theme         = "BlogRa"
languageCode  = "en-us"
title         = "OU Self Study Notes"

disqusShortname = ""

[params]
    description     = "Open University"
    contactEmail    = "your-email@domain.com"
    footer          = ""
    googleSearch    = "google-cse-key"
    googleAnalytics = ""      # Google Analytics v4
    adsense         = "adsense-key"
    math            = false   # best to enable this in the front matter of a page
    mermaid         = false   # best to enable this in the front matter of a page

    # Social Media Params
    github     = "https://github.com/KC-OU"

# Configure the site menu here
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "Posts"
                url = "/posts/"
                weight = 1
            [[menu.main]]
                parent = "blog"
                name = "Sections"
                url = "/sections/"
                weight = 2

[markup.goldmark.parser.attribute]
    block = true

# Don't touch this
[markup.goldmark.renderer]
    unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.102.3"